### ISSUE TITLE
Detect real RPIs on the network

### ISSUE THREAD

**Issue by julianxhokaxhiu** [dlion/WhereIsMyPi#1]
Based on your TODO I saw that maybe this library can help you on detecting MAC addresses on the network :)

http://godoc.org/code.google.com/p/gopacket

**Comment by dlion** [comment]
I want to avoid to use rawpackets et simila because it requires root privilege.
I thought to use the arp table present on my machine to identify MAC address.
So: Scan my subnet -> read /proc/net/arp -> identify MAC -> if is a raspberry print on screen.
This is the simplest thing that I can do without root privilege but in this way I remove the possibility to port my code in every os ( /proc/net/arp you know)
Mmh suggestions about it ?

**Comment by julianxhokaxhiu** [comment]
That package should help you on porting your project in a multi platform way without reading special OS paths...that's why I was suggesting it.
